version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/sdkdocs/source/conf.py

python:
  install:
    - requirements: docs/sdkdocs/requirements.txt

formats:
  - pdf
  - epub