name: Go Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/kubeflow/training-operator

    strategy:
      fail-fast: false
      matrix:
        # Detail: `setup-envtest list`
        kubernetes-version: ["1.27.1", "1.28.3", "1.29.1"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ${{ env.GOPATH }}/src/github.com/kubeflow/training-operator

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.GOPATH }}/src/github.com/kubeflow/training-operator/go.mod

      - name: Run Go test for v1
        run: |
          make test ENVTEST_K8S_VERSION=${{ matrix.kubernetes-version }}

      - name: Run Go test for v2
        run: |
          make test-integrationv2 ENVTEST_K8S_VERSION=${{ matrix.kubernetes-version }}

      - name: Coveralls report
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out
          working-directory: ${{ env.GOPATH }}/src/github.com/kubeflow/training-operator
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
